// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.');
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.');
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Mh8SOaenYHu_I2BGq4SZuVMq2MmV9mQ',
    appId: '1:324003989634:web:cultioo_business_web',
    messagingSenderId: '324003989634',
    projectId: 'cultioo-business-app',
    authDomain: 'cultioo-business-app.firebaseapp.com',
    storageBucket: 'cultioo-business-app.firebasestorage.app');

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Mh8SOaenYHu_I2BGq4SZuVMq2MmV9mQ',
    appId: '1:324003989634:android:cultioo_business_android',
    messagingSenderId: '324003989634',
    projectId: 'cultioo-business-app',
    storageBucket: 'cultioo-business-app.firebasestorage.app');

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Mh8SOaenYHu_I2BGq4SZuVMq2MmV9mQ',
    appId: '1:324003989634:ios:96fc409bc2534b2a428c9b',
    messagingSenderId: '324003989634',
    projectId: 'cultioo-business-app',
    storageBucket: 'cultioo-business-app.firebasestorage.app',
    iosBundleId: 'com.cultioo.BusinessApp');

  // TODO: Register macOS app in Firebase Console (same bundle ID: com.cultioo.BusinessApp)
  // and replace appId with the macOS-specific GOOGLE_APP_ID from the downloaded GoogleService-Info.plist.
  // For now, using the iOS app credentials (same Apple platform / same project) as a working fallback.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4Mh8SOaenYHu_I2BGq4SZuVMq2MmV9mQ',
    appId: '1:324003989634:ios:96fc409bc2534b2a428c9b',
    messagingSenderId: '324003989634',
    projectId: 'cultioo-business-app',
    storageBucket: 'cultioo-business-app.firebasestorage.app',
    iosBundleId: 'com.cultioo.BusinessApp');
}
